### PR TITLE
Add tvOS Support

### PR DESCRIPTION
**Pull request by jsclayton**
There doesn't appear to be anything specific to iOS that wouldn't run on tvOS so this becomes a simple podspec change.

### CODE REVIEW

**Comment by jsclayton** [comment]
I did...submitted to review this afternoon. I'm primarily using to show a loading spinner, which worked identically to iOS. I may add a retry button on failure as time permits.

**Comment by jsclayton** [comment]
Certainly! 

simulator screen shot jun 3 2016 9 54 28 am

simulator screen shot jun 3 2016 9 54 22 am

**Comment by jsclayton** [comment]
@dzenbot Sure...I'll try to make some time for it and send another PR. 👍

**Comment by doogilasovich** [comment]
Has this been pushed to the cocopods repo? When I try to use 'pod install' for this pod is get the error message
```
$ pod install
Analyzing dependencies
[!] The platform of the target `MY.TV.App` (tvOS 10.0) is not compatible with `DZNEmptyDataSet (1.8.1)`, which does not support `tvos`.
```

**Comment by joseangelrg30** [comment]
I'm getting also that is not compatible
`Analyzing dependencies
[!] The platform of the target `Cinema Uno TV` (tvOS 13.4) is not compatible with `DZNEmptyDataSet (1.8.1)`, which does not support `tvOS`.`

**Comment by joseangelrg30** [comment]
I think that somehow this change hasn't been pushed to the cocoapods repo, I have to use this in order to install it under tvOS
pod 'DZNEmptyDataSet', :git => 'https://github.com/dzenbot/DZNEmptyDataSet.git'

**Pull request merged**
