### PR TITLE
Fix collectionView internal error crash with EXC_BAD_ACCESS

### PR DESCRIPTION
**Pull request by m1entus**
This Could be related to issue #55 , i had some EXC_BAD_ACCESS, and i followed NSZombie profiling, and it look like that UIKit is doing something strange which is causing crash during rotation.

### CODE REVIEW

**Comment by m1entus** [comment]
This solved issue for me, i have little bit complicated view hierarchy, and couldn't find other solution. Only when i commented line with adding observer it didn't crash. NSZombie shows collectionView memory address and stacktrace shows me that UIKit library is releasing released object and ref count is -1

**Comment by m1entus** [comment]
Right,i forgot about it, anyway it would not crash because i used weak self, it will be memory leak because of not released opaque `id<NSObject` object as you said. I made a solution by swizzling dealloc method (yeah... really hacky) but works fine.

**Comment by joaopedrok** [comment]
Guys, i was trying to use dzn in swift and im getting thread bad access. I don't know how to fix it u guys can tell me?

**Comment by joaopedrok** [comment]
i discovered why. But i still dont know how to fix it. My applications is only in portrait it doesnt work in landscape mode. So when i rotate my device it crashes. Does anyone know what i need to do to fix it?

**Comment by m1entus** [comment]
I forgot to set emptyDataSet delegate to nil and seem to work fine

**Pull request closed without merging**
